# Generated by Django 6.1 on 2026-08-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='ending_explained',
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='none.jpg', upload_to='posters/'),
            preserve_default=False,
        ),
    ]
