# Generated by Django 6.1 on 2026-08-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_ending_explained_movie_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Marvel', 'Marvel'), ('Thriller', 'Thriller')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
